Vagrant.configure("2") do |config|
# You can use your own Vagrant boxes
  config.vm.box = "centos/7" 
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2024"
  end

# Modify shell commands as per your vagrant boxes docker installation
  config.vm.provision "shell", inline: <<-SHELL 
    yum install -y update
	yum install -y git
    yum install -y docker
	sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
    sudo chmod +x /usr/bin/docker-compose
    docker-compose version
	systemctl enable --now docker
	git clone https://github.com/sarath-pm/Vagrant-DockerCompose-LEMP-Wordpress.git
    cd docker-compose-lemp-wordpress
    docker-compose up -d
  SHELL
end
